import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePicture  from '../../public/images/profile/developer-pic-1.png'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
           <div className="flex justify-between items-center w-full">
              <div className="w-1/2">
              <Image src={profilePicture} alt="code" className="w-full h-auto" />
              </div>
               <div className="w-1/2 flex flex-col items-center self-center">
                <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left'></AnimatedText>
                 <p className='text-base font-medium my-4'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>
                 <div className='flex self-start mt-2 items-center'>
                   <Link  href="/dummy.pdf" className='flex itmes-center justify-center  bg-dark text-light p-2.5 px-6 rounded-lg font-semibold text-lg hover:text-dark hover:bg-light 
                   border-2 border-solid border-transparent hover:border-dark' download={true} target={"_blank"}>
                    Resume <LinkArrow className={'w-6 ml-1'}/>
                   </Link>
                   <Link  href="maileto:895257516@qq.com" target={"_blank"} className='font-medium text-dark underline capitalize ml-4'>Contact</Link>
                 </div>
               </div>
           </div>
        </Layout>
        <HireMe />
        <div className='w-24 absolute right-8 bottom-8 inline-block'>
          <Image src={lightBulb} className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
